components:
  schemas:
    HelmReleaseSpec:
      properties:
        chart:
          oneOf:
          - properties:
              git:
                description: Git URL e.g. git@github.com:org/repo
                format: git
                type: string
              path:
                description: Path inside the git repository where the Helm chart is
                type: string
              ref:
                description: Git branch, defaults to master
                type: string
              skipDepUpdate:
                description: If set, does not run 'dep' update (assume requirements.yaml
                  is already fulfilled)
                type: boolean
            required:
            - git
            - path
          - properties:
              chartPullSecret:
                properties:
                  name:
                    description: Helm repository basic auth (not implemented)
                    type: string
              name:
                description: Helm chart name
                type: string
              repository:
                description: Helm repository URL
                format: url
                type: string
              version:
                description: Helm chart version
                format: semver
                type: string
            required:
            - repository
            - name
            - version
        forceUpgrade:
          description: If supplied will force Helm upgrade through delete/recreate
          type: boolean
        helmVersion:
          description: The Helm version this release targets. If not supplied, it
            will default to v2.
          pattern: ^v[2,3]$
          type: string
        maxHistory:
          description: The maximum number of release revisions to keep, defaults to
            10
          format: int32
          type: integer
        releaseName:
          description: The Helm release name. If not supplied, it will be generated
            by affixing the namespace to the resource name.
          pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
          type: string
        resetValues:
          description: If supplied will reset values on helm upgrade
          type: boolean
        rollback:
          properties:
            disableHooks:
              description: If set, will prevent hooks from running during rollback
              type: boolean
            enable:
              description: If set, will perform rollbacks for this release on upgrade
                failures
              type: boolean
            force:
              description: If set, will force resource update through delete/recreate
                if needed
              type: boolean
            maxRetries:
              description: The maximum amount of retries that should be attempted
                for a rolled back release if retries are enabled, defaults to 5, 0
                equals infinite
              format: int64
              type: integer
            recreate:
              type: boolean
            retry:
              description: If set, the upgrade of a rolled back release will be retried
                until the maximum amount of retries is reached
              type: boolean
            timeout:
              description: Time in seconds to wait for any individual Kubernetes operation,
                defaults to 300 seconds
              format: int64
              type: integer
            wait:
              description: If set, will wait until the minimum number of Pods of a
                Deployment are in a ready state before marking the release as successful
              type: boolean
          type: object
        skipCRDs:
          description: If set, will skip CRD installation for Helm v3
          type: boolean
        targetNamespace:
          description: The Helm release namespace. If not supplied, the namespace
            will be the same as the resource namespace.
          pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
          type: string
        timeout:
          description: Helm install or upgrade timeout in seconds
          format: int64
          type: integer
        valueFileSecrets:
          description: Deprecated! Use valuesFrom.secretKeyRef instead
          items:
            properties:
              name:
                description: Name of the secret, must be in the same namespace as
                  the HelmRelease
                type: string
            required:
            - name
            type: object
          type: array
        values:
          description: content of values.yaml
          type: object
        valuesFrom:
          items:
            oneOf:
            - required:
              - configMapKeyRef
            - required:
              - secretKeyRef
            - required:
              - externalSourceRef
            - required:
              - chartFileRef
            properties:
              chartFileRef:
                properties:
                  optional:
                    description: If set, successful retrieval of the values file is
                      no longer mandatory
                    type: boolean
                  path:
                    description: path within the helm chart (from git repo) where
                      values.yaml is located
                    type: string
                required:
                - path
                type: object
              configMapKeyRef:
                properties:
                  key:
                    description: Key in the configmap to get the values from, defaults
                      to values.yaml
                    type: string
                  name:
                    description: Name of the configmap, must be in the same namespace
                      as the HelmRelease
                    type: string
                  namespace:
                    description: The namespace in which the configmap exists
                    type: string
                  optional:
                    description: If set, successful retrieval of the values file is
                      no longer mandatory
                    type: boolean
                required:
                - name
                type: object
              externalSourceRef:
                properties:
                  optional:
                    description: If set, successful retrieval of the values file is
                      no longer mandatory
                    type: boolean
                  url:
                    description: URL of the values.yaml
                    type: string
                required:
                - url
                type: object
              secretKeyRef:
                properties:
                  key:
                    description: Key in the secret to get the values from, defaults
                      to values.yaml
                    type: string
                  name:
                    description: Name of the secret, must be in the same namespace
                      as the HelmRelease
                    type: string
                  namespace:
                    description: The namespace in which the secret exists
                    type: string
                  optional:
                    description: If set, successful retrieval of the values file is
                      no longer mandatory
                    type: boolean
                required:
                - name
                type: object
            type: object
          type: array
        wait:
          description: Wait for an upgrade to complete before marking release as successful
          type: boolean
      required:
      - chart
    spec:
      type: Object
paths: {}
info:
  title: helmreleases.helm.fluxcd.io
  version: 1
openapi: 3.0.3
