/*
 * helmreleases.helm.fluxcd.io
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HelmReleaseSpecValueFileSecrets {
    /// Name of the secret, must be in the same namespace as the HelmRelease
    #[serde(rename = "name")]
    pub name: String,
}

impl HelmReleaseSpecValueFileSecrets {
    pub fn new(name: String) -> HelmReleaseSpecValueFileSecrets {
        HelmReleaseSpecValueFileSecrets {
            name,
        }
    }
}


