apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: watchers.vsix.me
spec:
  group: vsix.me
  names:
    kind: Watcher
    listKind: WatcherList
    plural: watchers
    singular: watcher
  scope: Cluster
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          description: A Herald Watcher
          properties:
            apiVersion:
              description: The version of watcher
              type: string
            spec:
              description: the watcher spec
              properties:
                watchers:
                  description: A list of items to watch
                  items:
                    properties:
                      targetKind:
                        description: The type of object to be watched
                        type: string
                      namespaces:
                        items:
                          type: string
                        nullable: true
                        description: A list of namespaces to watch for this object
                        type: array
                      selector:
                        description: a map of labels to search for
                        properties:
                          matchLabels:
                            description: a list of labels to match
                            additionalProperties:
                              type: string
                            type: object
                          matchExpressions:
                            description: a list of expressions to match
                            items:
                              properties:
                                key:
                                  description: name of key
                                  type: string
                                operator:
                                  description: operator
                                  type: string
                                values:
                                  items:
                                    type: string
                                  type: array
                              type: object
                            type: array
                        type: object
                      notifier:
                        description: how to notify on detected changes
                        properties:
                          url:
                            description: url to hit
                            type: string
                          method:
                            description: which method get/post/put
                            type: string
                          formatTemplate:
                            description: the template string to send to url
                            type: string
                        type: object
                    type: object
                  type: array
              type: object
          type: object
      served: true
      storage: true
