---
apiVersion: vsix.me/v1
kind: Watcher
metadata:
  name: testwatcher
  namespace: monitoring
  labels:
    app.kubernetes.io/name: herald
spec:
  watchers:
    - namespaces:
        - monitoring
      targetKind: Deployment
      selector:
        matchExpressions:
          - operator: In
            key: foo
            values:
              - foobar
        matchLabels:
          hello: goodbye
          app.kubernetes.io/name: herald
      notifier:
        url: http://vsix.me
        method: POST
        formatTemplate: "foobar"
