---
apiVersion: vsix.me/v1
kind: Watcher
metadata:
  name: testwatcher
  namespace: monitoring
  labels:
    app.kubernetes.io/name: herald
spec:
  watchers:
    - namespaces:
        - monitoring
      targetKind: Deployment
      selector:
        matchExpressions: []
        matchLabels:
          app.kubernetes.io/name: herald
      notifier:
        url: https://hooks.slack.com/services/T9VAA3L59/B018R9WEMNJ/foobar
        method: POST
        formatTemplate: '{"text":"Detected a change to {{kind}}/{{metadata.name}}: image is set to {{spec.template.spec.containers.[0].image}}"}'
