name: pr-code-test-and-coverage
true:
  pull_request:
    branches:
    - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: run cargo tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-fail-fast
      env:
        CARGO_INCREMENTAL: "0"
        RUSTFLAGS: -Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code
          -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests
        RUSTDOCFLAGS: -Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code
          -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests
    - name: Run grcov
      uses: actions-rs/grcov@v0.1
      with:
        config: build-configs/grcov.yml
    - name: Coveralls upload
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ steps.coverage.outputs.report }}
